import {
  Bell,
  Box,
  CircleCheck,
  DataAnalysis,
  Goods,
  ShoppingCart,
  Tickets,
} from '@element-plus/icons-vue';
import type { DashboardShortcut } from './dashboard.types';

export const DASHBOARD_SHORTCUTS: DashboardShortcut[] = [
  {
    key: 'sales-orders',
    title: '销售订单',
    description: '查询与处理客户订单',
    path: '/sales/orders',
    pagePermission: 'sales:orders',
    icon: Goods,
  },
  {
    key: 'purchase-orders',
    title: '采购订单',
    description: '查看采购执行情况',
    path: '/purchase/orders',
    pagePermission: 'purchase:orders',
    icon: ShoppingCart,
  },
  {
    key: 'inventory-stocks',
    title: '库存查询',
    description: '查看仓库即时库存',
    path: '/inventory/stocks',
    pagePermission: 'inventory:stocks',
    icon: Box,
  },
  {
    key: 'production-plans',
    title: '生产计划',
    description: '查看生产与缺料状态',
    path: '/production/plans',
    pagePermission: 'production:plans',
    icon: DataAnalysis,
  },
  {
    key: 'purchase-receipts',
    title: '采购入库',
    description: '快速创建采购入库单',
    path: '/purchase/receipts',
    create: true,
    pagePermission: 'purchase:receipts',
    actionPermission: 'purchase:receipts:create',
    icon: ShoppingCart,
  },
  {
    key: 'sales-outputs',
    title: '销售出库',
    description: '快速创建销售出库单',
    path: '/sales/outputs',
    create: true,
    pagePermission: 'sales:outputs',
    actionPermission: 'sales:outputs:create',
    icon: Goods,
  },
  {
    key: 'requisition-applications',
    title: '领用申请',
    description: '快速发起物资领用',
    path: '/requisitions/applications',
    create: true,
    pagePermission: 'requisitions:applications',
    actionPermission: 'requisitions:applications:create',
    icon: Tickets,
  },
  {
    key: 'inventory-checks',
    title: '库存盘点',
    description: '快速创建库存盘点单',
    path: '/inventory/checks',
    create: true,
    pagePermission: 'inventory:checks',
    actionPermission: 'inventory:checks:create',
    icon: CircleCheck,
  },
  {
    key: 'dashboard-messages',
    title: '消息中心',
    description: '查看审批与预警消息',
    path: '/dashboard/messages',
    pagePermission: 'dashboard:3:view',
    icon: Bell,
  },
];
