export type BusinessColumn = {
  prop: string;
  label: string;
  width?: number;
  minWidth?: number;
  kind?: 'date' | 'datetime' | 'money' | 'number' | 'status' | 'progress' | 'text';
};
export type BusinessConfig = {
  title: string;
  no: string;
  columns: BusinessColumn[];
  dictionaries?: string[];
  summary?: boolean;
  creatable?: boolean;
  createText?: string;
};

const c = (
  prop: string,
  label: string,
  minWidth = 110,
  kind: BusinessColumn['kind'] = 'text',
): BusinessColumn => ({ prop, label, minWidth, kind });
const dt = (prop: string, label: string = '操作时间') => c(prop, label, 150, 'datetime');
const date = (prop: string, label: string = '日期') => c(prop, label, 110, 'date');
const money = (prop: string, label: string) => c(prop, label, 120, 'money');
const num = (prop: string, label: string) => c(prop, label, 105, 'number');
const status = (prop: string, label: string = '状态') => c(prop, label, 105, 'status');

export const businessConfigs: Record<string, BusinessConfig> = {
  'production/boms': {
    title: 'BOM 编排',
    no: 'bomNo',
    dictionaries: ['enabled_status'],
    columns: [
      c('bomNo', 'BOM编号', 140),
      c('bomName', 'BOM名称', 160),
      c('goodsCode', '成品编码', 110),
      c('goodsName', '成品名称', 135),
      c('categoryName', '分类', 100),
      c('unitName', '单位', 65),
      num('materialCount', '原料种数'),
      c('updatedByName', '操作人'),
      dt('updatedAt'),
      status('statusName', '状态'),
    ],
  },
  'production/plans': {
    title: '生产计划单',
    no: 'planNo',
    dictionaries: [
      'production_plan_status',
      'production_material_status',
      'production_stock_check_status',
      'production_outbound_status',
      'approval_status',
    ],
    columns: [
      c('planNo', '生产计划单号', 155),
      c('sourceOrderNo', '关联销售订单', 155),
      c('bomNo', 'BOM编号', 135),
      c('goodsName', '生产成品', 145),
      num('planQty', '生产数量'),
      c('deliveryProgress', '交付进度', 120, 'progress'),
      c('warehouseName', '仓库', 125),
      date('planDate', '日期'),
      c('updatedByName', '操作人'),
      dt('updatedAt'),
      status('status', '状态'),
    ],
  },
  'production/outputs': {
    title: '生产出库单',
    no: 'outNo',
    summary: true,
    createText: '新增临时出库',
    dictionaries: [
      'production_material_out_type',
      'temporary_outbound_destination',
      'confirm_status',
    ],
    columns: [
      c('outNo', '单据编号', 155),
      status('outTypeName', '出库类型'),
      c('destinationTypeName', '出库去向', 100),
      c('planNo', '来源生产计划', 150),
      c('bomNo', 'BOM编号', 140),
      c('goodsName', '生产成品', 140),
      num('materialCount', '原料种数'),
      c('stockCheckStatus', '库存校验', 100),
      c('warehouseName', '仓库', 125),
      date('outDate', '日期'),
      c('updatedByName', '操作人'),
      dt('updatedAt'),
      status('statusName', '状态'),
    ],
  },
  'production/inputs': {
    title: '生产成品入库单',
    no: 'inputNo',
    columns: [
      c('inputNo', '成品入库单号', 160),
      c('planNo', '来源生产计划', 155),
      c('goodsName', '入库成品', 145),
      num('quantity', '本次入库'),
      c('warehouseName', '仓库', 125),
      date('inputDate', '日期'),
      c('updatedByName', '操作人'),
      dt('updatedAt'),
      status('statusName', '状态'),
    ],
  },
  'production/shortages': {
    title: '生产缺料清单',
    no: 'shortageNo',
    dictionaries: ['production_shortage_status'],
    creatable: false,
    columns: [
      c('shortageNo', '缺料清单编号', 155),
      c('planNo', '生产计划', 145),
      c('productGoodsName', '生产成品', 130),
      c('goodsCode', '原料编码', 120),
      c('goodsName', '原料名称', 145),
      num('requireQty', '总需求'),
      num('factQty', '当前库存'),
      num('gapQty', '缺口数量'),
      num('purchaseQty', '建议采购数量'),
      c('purchaseId', '采购申请', 130),
      c('updatedByName', '操作人'),
      dt('updatedAt'),
      status('statusName', '状态'),
    ],
  },
  'sales/orders': {
    title: '销售订单',
    no: 'orderNo',
    dictionaries: [
      'sales_order_type',
      'sales_order_source',
      'sales_order_property',
      'sales_order_status',
      'sales_delivery_status',
      'sales_service_status',
      'sales_payment_progress_status',
    ],
    columns: [
      c('orderNo', '订单号', 155),
      c('customerName', '客户', 130),
      c('goodsNames', '商品名称', 180),
      status('sourceTypeName', '订单来源'),
      status('propertyTypeName', '订单属性'),
      date('orderDate', '订单日期'),
      num('quantity', '订单数量'),
      money('orderAmount', '订单金额'),
      money('amount', '实际金额'),
      money('receivedAmount', '累计收款'),
      money('refundedAmount', '累计退款'),
      money('netAmount', '净收款'),
      c('paymentStatus', '收款状态', 100),
      c('deliveryProgress', '发货进度', 110, 'progress'),
      status('serviceStatusName', '售后状态'),
      c('createdByName', '创建人'),
      dt('createdAt'),
      status('orderStatusName', '订单状态'),
    ],
  },
  'sales/outputs': {
    title: '销售出库单',
    no: 'businessNo',
    dictionaries: ['sales_output_destination', 'confirm_status'],
    columns: [
      c('businessNo', '出库单号', 160),
      c('orderNo', '销售订单', 155),
      c('customerName', '客户', 130),
      c('warehouseName', '仓库', 125),
      date('date', '出库日期'),
      num('quantity', '本次出库'),
      status('confirmStatusName', '确认状态'),
      c('createdByName', '创建人'),
      dt('createdAt'),
    ],
  },
  'sales/returns': {
    title: '销售退货单',
    no: 'businessNo',
    dictionaries: ['sales_return_disposal', 'confirm_status'],
    columns: [
      c('businessNo', '退货单号', 160),
      c('orderNo', '销售订单', 155),
      c('sourceOutputNo', '来源出库单', 135),
      c('customerName', '客户', 130),
      c('warehouseName', '仓库', 125),
      date('date', '退货日期'),
      num('quantity', '退货数量'),
      status('disposalTypeName', '退货后处理'),
      status('confirmStatusName', '确认状态'),
      c('createdByName', '创建人'),
      dt('createdAt'),
    ],
  },
  'sales/payments': {
    title: '销售收款',
    no: 'paymentNo',
    summary: true,
    dictionaries: ['payment_channel', 'sales_payment_type'],
    columns: [
      c('paymentNo', '收款单号', 160),
      c('orderNo', '销售订单', 155),
      c('customerName', '客户', 130),
      money('orderActualAmount', '订单实际金额'),
      money('receivedAmount', '累计收款'),
      money('refundedAmount', '累计退款'),
      money('availableAmount', '未收金额'),
      money('amount', '本次收款'),
      status('paymentModeName', '付款方式'),
      date('paymentDate', '收款日期'),
      c('orgName', '组织', 125),
      c('deptName', '部门', 125),
      c('createdByName', '操作人'),
      dt('createdAt'),
    ],
  },
  'sales/refunds': {
    title: '销售退款',
    no: 'paymentNo',
    summary: true,
    dictionaries: ['payment_channel', 'sales_payment_type'],
    columns: [
      c('paymentNo', '退款单号', 160),
      c('orderNo', '销售订单', 155),
      c('customerName', '客户', 130),
      money('receivedAmount', '累计收款'),
      money('refundedAmount', '累计退款'),
      money('netAmount', '净收款'),
      money('availableAmount', '可退金额'),
      money('amount', '本次退款'),
      status('paymentModeName', '退款方式'),
      date('paymentDate', '退款日期'),
      c('remark', '退款原因', 160),
      c('orgName', '组织', 125),
      c('deptName', '部门', 125),
      c('createdByName', '操作人'),
      dt('createdAt'),
    ],
  },
  'sales/discount-orders': {
    title: '折价销售单',
    no: 'orderNo',
    dictionaries: [
      'sales_order_source',
      'sales_order_status',
      'sales_discount_disposal_status',
      'sales_business_source_type',
    ],
    columns: [
      c('orderNo', '折价销售单号', 165),
      c('businessSourceType', '来源类型', 120),
      c('businessSourceNo', '来源单号', 145),
      c('customerName', '客户', 130),
      c('goodsNames', '商品名称', 180),
      c('warehouseName', '仓库', 120),
      date('orderDate'),
      money('amount', '最终成交金额'),
      c('createdByName', '创建人'),
      status('discountDisposalStatus'),
    ],
  },
  'sales/services': {
    title: '售后记录',
    no: 'serviceNo',
    dictionaries: ['after_sale_event_type', 'after_sale_event_status'],
    columns: [
      c('serviceNo', '服务编号', 155),
      c('sourceSystemName', '售后来源', 110),
      c('externalRequestNo', '外部申请号', 150),
      c('orderNo', '销售订单', 155),
      c('customerName', '客户', 130),
      c('goodsName', '商品', 145),
      status('eventTypeName', '事件类型'),
      c('eventContent', '事件内容', 220),
      c('handlerIdName', '处理人'),
      date('eventDate', '事件日期'),
      status('eventStatusName'),
    ],
  },
  'requisitions/applications': {
    title: '领用申请单',
    no: 'applicationNo',
    dictionaries: ['draw_type', 'requisition_status', 'requisition_approval_status', 'yes_no'],
    columns: [
      c('applicationNo', '申请单号', 160),
      c('deptName', '领用部门', 130),
      c('receiverIdName', '领用人', 110),
      c('warehouseName', '仓库', 125),
      status('drawTypeName', '领用类型'),
      date('date', '申请日期'),
      num('quantity', '申请总量'),
      num('actualQty', '实际领用'),
      status('approveStatusName', '审批状态'),
      status('oaStatusName', 'OA状态'),
      c('createdByName', '创建人'),
      dt('createdAt'),
    ],
  },
  'requisitions/outputs': {
    title: '领用出库单',
    no: 'outputNo',
    dictionaries: ['requisition_confirm_status'],
    columns: [
      c('outputNo', '出库单号', 160),
      c('applicationNo', '来源申请', 155),
      c('deptName', '领用部门', 130),
      c('receiverIdName', '接收人', 110),
      c('warehouseName', '仓库', 125),
      date('outDate', '出库日期'),
      num('applicationQty', '申请数量'),
      num('quantity', '实出数量'),
      status('confirmStatusName', '确认状态'),
      c('createdByName', '创建人'),
      dt('createdAt'),
    ],
  },
  'requisitions/returns': {
    title: '领用退回单',
    no: 'returnNo',
    dictionaries: ['requisition_status', 'requisition_confirm_status'],
    columns: [
      c('returnNo', '退回单号', 160),
      c('outputNo', '来源出库单', 155),
      c('applicationNo', '领用申请', 155),
      c('deptName', '领用部门', 130),
      c('receiverIdName', '经办人', 110),
      c('warehouseName', '仓库', 125),
      date('returnDate', '退回日期'),
      num('quantity', '退回数量'),
      status('confirmStatusName', '确认状态'),
      c('createdByName', '创建人'),
      dt('createdAt'),
    ],
  },
};
