export type OaFormFieldMapping = {
  readonly componentType: string;
  readonly uniqueName: string;
  readonly child: boolean;
};

export type OaFormMapping = {
  readonly businessType: string;
  readonly formKey: string;
  readonly formId: string;
  readonly fields: Readonly<Record<string, OaFormFieldMapping>>;
};

const field = (componentType: string, uniqueName: string, child = false) => ({
  componentType,
  uniqueName,
  child,
});

/**
 * 2026-08-12 从薪福通 OA 已发布表单实时核对的字段注册表。
 * formKey 用于发起流程；formId 用于标识本次核对的已发布版本。
 */
export const OA_FORM_MAPPINGS = {
  purchase_application: {
    businessType: 'purchase_application',
    formKey: 'AAC15400_NFORM_380054577920868353',
    formId: '380192373354790912',
    fields: {
      reason: field('FinInput', 'dhi6d3c7oecn'),
      warehouse: field('FinInput', 'iluym6g473ox'),
      source: field('FinInput', 'jg2zwug75y3c'),
      remark: field('FinTextArea', 'tp1teg5kd21y'),
      attachments: field('FinUpload', 'pc744eoan0wp'),
      details: field('FinTable', 'vdd3e94g4ho9'),
      goodsName: field('FinInput', 'qotb3suzfb82', true),
      skuName: field('FinInput', '4a0wvks0vr2o', true),
      quantity: field('FinInputNumber', 'fzc9rr3c5a6e', true),
      unit: field('FinInput', '2kq65w37r24o', true),
      detailRemark: field('FinInput', '8avk96xhktxy', true),
    },
  },
  purchase_return: {
    businessType: 'purchase_return',
    formKey: 'AAC15400_NFORM_380055155598098472',
    formId: '380055728969678848',
    fields: {
      returnDate: field('FinDatePicker', '2yr7fsze3kf9'),
      returnType: field('FinInput', 'iluym6g473ox'),
      reason: field('FinTextArea', 'tp1teg5kd21y'),
      sourceReceipt: field('FinInput', '8aqmty9l4urc'),
      sourcePurchaseOrder: field('FinInput', 'xaferqjxcr12'),
      remark: field('FinTextArea', 'gqnr94fw22oe'),
      attachments: field('FinUpload', 'sncn26am87y3'),
      details: field('FinTable', 'vdd3e94g4ho9'),
      goodsName: field('FinInput', 'qotb3suzfb82', true),
      skuName: field('FinInput', '4a0wvks0vr2o', true),
      batchNo: field('FinInput', '3n9goiuucnkx', true),
      quantity: field('FinInputNumber', 'ybvomk2fvzff', true),
      unit: field('FinInput', 'v58dp5a7i4ge', true),
      detailRemark: field('FinInput', 'heuxl9q5nf0b', true),
    },
  },
  inventory_transfer: {
    businessType: 'inventory_transfer',
    formKey: 'AAC15400_NFORM_380056143439593472',
    formId: '380193193693544450',
    fields: {
      transferDate: field('FinDatePicker', '2yr7fsze3kf9'),
      reason: field('FinTextArea', '2529b3mgtnva'),
      sourceOrganization: field('FinInput', '8aqmty9l4urc'),
      sourceWarehouse: field('FinInput', 'xaferqjxcr12'),
      targetOrganization: field('FinInput', '96gx3xc2mbxn'),
      targetWarehouse: field('FinInput', '7cjed7tx7vn2'),
      sender: field('FinPeopleSelect', 'lryp0thutg9z'),
      receiver: field('FinPeopleSelect', 'x1lff5wg5wzl'),
      remark: field('FinTextArea', 'sz1u0r3unzop'),
      attachments: field('FinUpload', 's46nioz4eqcm'),
      details: field('FinTable', 'vdd3e94g4ho9'),
      goodsName: field('FinInput', 'qotb3suzfb82', true),
      skuName: field('FinInput', '4a0wvks0vr2o', true),
      batchNo: field('FinInput', '3n9goiuucnkx', true),
      quantity: field('FinInputNumber', 'ybvomk2fvzff', true),
      unit: field('FinInput', 'v58dp5a7i4ge', true),
    },
  },
  inventory_adjust: {
    businessType: 'inventory_adjust',
    formKey: 'AAC15400_NFORM_380056968068399104',
    formId: '380056968066826240',
    fields: {
      applicationDate: field('FinDatePicker', '2yr7fsze3kf9'),
      reason: field('FinInput', 'iluym6g473ox'),
      remark: field('FinTextArea', 'sz1u0r3unzop'),
      attachments: field('FinUpload', 's46nioz4eqcm'),
      details: field('FinTable', 'vdd3e94g4ho9'),
      warehouse: field('FinInput', '6278m4nx9ipy', true),
      goodsName: field('FinInput', 'qotb3suzfb82', true),
      skuName: field('FinInput', '4a0wvks0vr2o', true),
      batchNo: field('FinInput', '3n9goiuucnkx', true),
      adjustType: field('FinInput', '5dtuwgmokxri', true),
      beforeQuantity: field('FinInputNumber', 'ybvomk2fvzff', true),
      adjustQuantity: field('FinInputNumber', 'pi9j28c4si7v', true),
      afterQuantity: field('FinInputNumber', 'mgwgzikto2kj', true),
      detailRemark: field('FinInput', 'v58dp5a7i4ge', true),
    },
  },
  inventory_check: {
    businessType: 'inventory_check',
    formKey: 'AAC15400_NFORM_380057975245897728',
    formId: '380057975236657152',
    fields: {
      checkType: field('FinInput', 'eeujb69pcrtx'),
      checkDate: field('FinDatePicker', '2yr7fsze3kf9'),
      organization: field('FinInput', 'iluym6g473ox'),
      warehouse: field('FinInput', '8aqmty9l4urc'),
      bookQuantity: field('FinInputNumber', 'idkj8yop1lf8'),
      bookAmount: field('FinMoney', 'fakb3dvdv4xz'),
      lossQuantity: field('FinInputNumber', 'v5epv2773y3w'),
      lossAmount: field('FinMoney', 'smvwjxvmdr0z'),
      overflowQuantity: field('FinInputNumber', 'tp68r8bc2obm'),
      overflowAmount: field('FinMoney', '9xl2j6n4tvwq'),
      remark: field('FinTextArea', 'sz1u0r3unzop'),
      attachments: field('FinUpload', 's46nioz4eqcm'),
      details: field('FinTable', 'vdd3e94g4ho9'),
      goodsName: field('FinInput', 'qotb3suzfb82', true),
      skuName: field('FinInput', '4a0wvks0vr2o', true),
      batchNo: field('FinInput', '3n9goiuucnkx', true),
      detailBookQuantity: field('FinInputNumber', 'ybvomk2fvzff', true),
      actualQuantity: field('FinInputNumber', 'aefd9r3w4atu', true),
      damagedQuantity: field('FinInputNumber', 'joawaaqna4pt', true),
      differenceQuantity: field('FinInputNumber', '8vzhtxbhakt4', true),
      unit: field('FinInput', 'uoo0isvdc9y1', true),
      differenceAmount: field('FinMoney', 'in4wvogtvdzf', true),
      detailRemark: field('FinInput', 'ixgthz2sg4b7', true),
    },
  },
  inventory_loss: {
    businessType: 'inventory_loss',
    formKey: 'AAC15400_NFORM_380058048260145259',
    formId: '380064275954597888',
    fields: {
      businessCategory: field('FinInput', 'eeujb69pcrtx'),
      lossType: field('FinInput', '64z8akrtng2a'),
      lossDate: field('FinDatePicker', '02c6unm5y727'),
      organization: field('FinInput', 'iluym6g473ox'),
      department: field('FinInput', '8aqmty9l4urc'),
      warehouse: field('FinInput', 'lyx1ey483c5u'),
      reason: field('FinTextArea', 'ay295j2jhfes'),
      totalQuantity: field('FinInputNumber', 'idkj8yop1lf8'),
      totalAmount: field('FinMoney', 'fakb3dvdv4xz'),
      disposalDestination: field('FinInput', 'q1l417kfmtum'),
      sourceCheck: field('FinInput', '6wyisiccf7ai'),
      remark: field('FinTextArea', 'sz1u0r3unzop'),
      attachments: field('FinUpload', 's46nioz4eqcm'),
      details: field('FinTable', 'vdd3e94g4ho9'),
      goodsName: field('FinInput', 'qotb3suzfb82', true),
      skuName: field('FinInput', '4a0wvks0vr2o', true),
      batchNo: field('FinInput', '3n9goiuucnkx', true),
      quantity: field('FinInputNumber', 'ybvomk2fvzff', true),
      unit: field('FinInput', 'uoo0isvdc9y1', true),
      amount: field('FinMoney', 'in4wvogtvdzf', true),
    },
  },
  inventory_loss_output: {
    businessType: 'inventory_loss_output',
    formKey: 'AAC15400_NFORM_380058774110011394',
    formId: '380192560184557568',
    fields: {
      lossType: field('FinInput', 'ap7cuxi0ux2h'),
      lossDate: field('FinDatePicker', '02c6unm5y727'),
      organization: field('FinInput', 'iluym6g473ox'),
      department: field('FinInput', '8aqmty9l4urc'),
      warehouse: field('FinInput', 'lyx1ey483c5u'),
      reason: field('FinTextArea', 'ay295j2jhfes'),
      totalQuantity: field('FinInputNumber', 'idkj8yop1lf8'),
      totalAmount: field('FinMoney', 'fakb3dvdv4xz'),
      sourceLoss: field('FinInput', 'q1l417kfmtum'),
      sourceCheck: field('FinInput', '6wyisiccf7ai'),
      remark: field('FinTextArea', 'sz1u0r3unzop'),
      attachments: field('FinUpload', 's46nioz4eqcm'),
      details: field('FinTable', 'vdd3e94g4ho9'),
      goodsName: field('FinInput', 'qotb3suzfb82', true),
      skuName: field('FinInput', '4a0wvks0vr2o', true),
      batchNo: field('FinInput', '3n9goiuucnkx', true),
      quantity: field('FinInputNumber', 'ybvomk2fvzff', true),
      unit: field('FinInput', 'uoo0isvdc9y1', true),
      amount: field('FinMoney', 'in4wvogtvdzf', true),
    },
  },
  inventory_overflow: {
    businessType: 'inventory_overflow',
    formKey: 'AAC15400_NFORM_380058814911807488',
    formId: '380192624609067008',
    fields: {
      overflowType: field('FinInput', 'jdywqu2fs3n6'),
      overflowDate: field('FinDatePicker', '02c6unm5y727'),
      organization: field('FinInput', 'iluym6g473ox'),
      department: field('FinInput', '8aqmty9l4urc'),
      warehouse: field('FinInput', 'lyx1ey483c5u'),
      reason: field('FinTextArea', 'ay295j2jhfes'),
      totalQuantity: field('FinInputNumber', 'idkj8yop1lf8'),
      totalAmount: field('FinMoney', 'fakb3dvdv4xz'),
      sourceCheck: field('FinInput', 'q1l417kfmtum'),
      remark: field('FinTextArea', 'sz1u0r3unzop'),
      attachments: field('FinUpload', 's46nioz4eqcm'),
      details: field('FinTable', 'vdd3e94g4ho9'),
      goodsName: field('FinInput', 'qotb3suzfb82', true),
      skuName: field('FinInput', '4a0wvks0vr2o', true),
      batchNo: field('FinInput', '3n9goiuucnkx', true),
      quantity: field('FinInputNumber', 'ybvomk2fvzff', true),
      unit: field('FinInput', 'uoo0isvdc9y1', true),
      amount: field('FinMoney', 'in4wvogtvdzf', true),
    },
  },
  production_plan: {
    businessType: 'production_plan',
    formKey: 'AAC15400_NFORM_380059016770420777',
    formId: '380192693329854464',
    fields: {
      organization: field('FinInput', 'iluym6g473ox'),
      product: field('FinInput', '8aqmty9l4urc'),
      skuName: field('FinInput', 'lyx1ey483c5u'),
      bom: field('FinInput', 'zbbm9vljgrxm'),
      quantity: field('FinInputNumber', 'mc9sazh05agn'),
      planDate: field('FinDatePicker', 'g6nh2haocgdt'),
      materialWarehouse: field('FinInput', 'q1l417kfmtum'),
      finishedWarehouse: field('FinInput', '96t3po6a0fym'),
      source: field('FinInput', 'h9nqhntaapl4'),
      remark: field('FinTextArea', 'sz1u0r3unzop'),
      attachments: field('FinUpload', 's46nioz4eqcm'),
      details: field('FinTable', 'vdd3e94g4ho9'),
      materialName: field('FinInput', 'qotb3suzfb82', true),
      materialSkuName: field('FinInput', '4a0wvks0vr2o', true),
      bomUnitQuantity: field('FinInputNumber', 'ybvomk2fvzff', true),
      standardQuantity: field('FinInputNumber', 'zsq8888zuamx', true),
      requiredQuantity: field('FinInputNumber', 'hmeouup33s0a', true),
      plannedOutputQuantity: field('FinInputNumber', 'xtw7xtrm3cpp', true),
      unit: field('FinInput', 'uoo0isvdc9y1', true),
      detailRemark: field('FinInput', '9uldb4mfgbmd', true),
    },
  },
  requisition_application: {
    businessType: 'requisition_application',
    formKey: 'AAC15400_NFORM_380014832305831937',
    formId: '380192935994458112',
    fields: {
      organization: field('FinInput', 'vwzkeepgpoz8'),
      department: field('FinInput', 'zewg1fv7smsj'),
      drawType: field('FinInput', 'gnhh5hy450ko'),
      warehouse: field('FinInput', '405ncqs7i1t1'),
      applicant: field('FinPeopleSelect', '51c0cg9xhbzv'),
      applicationDate: field('FinDatePicker', 'ig65sy4c1pr2'),
      reason: field('FinTextArea', 'nvm0e6c6sezz'),
      attachments: field('FinUpload', '9d9x9fg3tmg4'),
      details: field('FinTable', '92c4it1x97yp'),
      goodsName: field('FinInput', '6a30y3q8ar2v', true),
      quantity: field('FinInputNumber', 'xn9kyuz6yi46', true),
    },
  },
  sales_order: {
    businessType: 'sales_order',
    formKey: 'AAC15400_NFORM_380061383308804096',
    formId: '380061383294124032',
    fields: {
      organization: field('FinInput', 'vwzkeepgpoz8'),
      customerName: field('FinInput', 'zewg1fv7smsj'),
      orderDate: field('FinDatePicker', 'ig65sy4c1pr2'),
      salesperson: field('FinInput', 'gnhh5hy450ko'),
      warehouse: field('FinInput', '405ncqs7i1t1'),
      totalQuantity: field('FinInputNumber', '4fs9hl3zcq03'),
      originalAmount: field('FinMoney', '6244k2lh2ctw'),
      transactionAmount: field('FinMoney', 'j73794bmhvwb'),
      discountAmount: field('FinMoney', 'lkiu8y99stxq'),
      source: field('FinInput', 'h79q090vsr0x'),
      remark: field('FinTextArea', 'nvm0e6c6sezz'),
      attachments: field('FinUpload', '9d9x9fg3tmg4'),
      details: field('FinTable', '92c4it1x97yp'),
      goodsName: field('FinInput', '6a30y3q8ar2v', true),
      skuName: field('FinInput', 'ux8eagoyk6vc', true),
      quantity: field('FinInputNumber', 'xn9kyuz6yi46', true),
      unit: field('FinInput', 'iyqw8ch8yn3g', true),
      originalUnitPrice: field('FinMoney', '4vdymmmu7yzs', true),
      transactionUnitPrice: field('FinMoney', 'vpq6f4moncjc', true),
      originalLineAmount: field('FinMoney', 'mup2n8dyjc4a', true),
      transactionLineAmount: field('FinMoney', 'bbqw8gee147u', true),
    },
  },
} as const satisfies Readonly<Record<string, OaFormMapping>>;

export type OaBusinessType = keyof typeof OA_FORM_MAPPINGS;
